LOCAL_SHARED_LIBRARIES := libts
LOCAL_PRELINK_MODULE := false

LOCAL_C_INCLUDES:= \
	$(LOCAL_PATH)/android \
	$(LOCAL_PATH)/src

LOCAL_MODULE_PATH := $(TARGET_OUT_DATA_SHARED_LIBRARIES)/$(TS_PLUG)
#LOCAL_UNSTRIPPED_PATH := $(TARGET_ROOT_OUT_SBIN_UNSTRIPPED)

include $(BUILD_SHARED_LIBRARY)

